# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TwitDA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitDA
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'TwitterKit', '~> 3.3'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

end
